### ISSUE TITLE
Needing to chown files after starting a release

### ISSUE THREAD

**Issue by vordimous** [HDBandit/gitflow-release-action#3]
I have been using this action with the below workaround. Do you have an idea why the GithubAction actor loses permission after the release is started?

Here is the section of my action where I need to `chown` to make any edits to files before completing the release. 
```yaml
      - name: merge and tag ${{ steps.new-version.outputs.tag }}
        uses: HDBandit/gitflow-release-action@v2.0.10
        with:
          command: start
          tag: ${{ steps.new-version.outputs.tag }}
          main_branch: main

      - name: set owner of current branch # TODO: might be a symptom of the gitflow-release-action script
        run: sudo chown -R $(whoami) ${{ github.workspace }};

      - name: increment package.json version
        run: npm version ${{ steps.new-version.outputs.version }} --git-tag-version=false
...
      - name: merge and tag ${{ steps.new-version.outputs.tag }}
        uses: HDBandit/gitflow-release-action@v2.0.10
        with:
          command: finish
          tag: ${{ steps.new-version.outputs.tag }}
          main_branch: main
```
